-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero AssetTypeBookDepreciationSettings
--  Generated: 28‑May‑2025
--  Notes:
--    * One row per depreciation book (ACCOUNTING or TAX) for each Asset Type.
--    * Composite business key: asset_type_id + book_type.
--    * Surrogate key uses BIGINT IDENTITY (no SERIAL).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
-- =============================================================

/* -------------------------------------------------------------
   ods.asset_type_book_depreciation_settings – SCD‑2 per‑book
   depreciation configuration inherited by assets of this type
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.asset_type_book_depreciation_settings (
    /* --- Composite business key ----------------------------- */
    asset_type_id                     UUID NOT NULL,  -- FK to asset_types
    book_type                         VARCHAR(12) NOT NULL
                                        CHECK (book_type IN ('ACCOUNTING','TAX')),

    /* --- Depreciation parameters ---------------------------- */
    depreciation_method               VARCHAR(30)
                                        CHECK (depreciation_method IN ('STRAIGHT_LINE','DIMINISHING_VALUE','NONE')),
    depreciation_calculation_method   VARCHAR(10)
                                        CHECK (depreciation_calculation_method IN ('RATE','LIFE')),
    depreciation_rate                 NUMERIC(7,4) CHECK (depreciation_rate >= 0),
    useful_life_years                 INTEGER CHECK (useful_life_years >= 0),
    averaging_method                  VARCHAR(15)
                                        CHECK (averaging_method IN ('FULL_MONTH','DAILY','NONE')),
    residual_value                    NUMERIC(18,2) CHECK (residual_value >= 0),
    depreciation_start_date           DATE,
    created_date_utc                  TIMESTAMPTZ,
    updated_date_utc                  TIMESTAMPTZ,

    /* --- Tenant link --------------------------------------- */
    organisation_id                   UUID NOT NULL,

    /* --- SCD‑2 infrastructure ------------------------------- */
    surrogate_key     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from        TIMESTAMPTZ NOT NULL,
    valid_to          TIMESTAMPTZ NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current        BOOLEAN NOT NULL DEFAULT TRUE,

    /* --- Audit & status ------------------------------------ */
    fetched_at                      TIMESTAMPTZ NOT NULL,
    row_created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status                   ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking --------------------------- */
    batch_id                        UUID NOT NULL,
    landing_table_name              VARCHAR(255) NOT NULL,
    landing_record_identifier       VARCHAR(512) NOT NULL,
    raw_table_name                  VARCHAR(255),
    api_call_id                     UUID,
    source_system_id                VARCHAR(100),
    source_record_modified_at       TIMESTAMPTZ,

    /* --- Constraints --------------------------------------- */
    CONSTRAINT uq_asset_type_book_depr_business_key_current
        UNIQUE (asset_type_id, book_type, is_current) WHERE is_current,

    CONSTRAINT ck_asset_type_book_depr_valid_dates
        CHECK (valid_from < valid_to),

    CONSTRAINT ck_asset_type_book_depr_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED'))
);

/* --- Foreign Keys ------------------------------------------- */
ALTER TABLE ods.asset_type_book_depreciation_settings
    ADD CONSTRAINT fk_asset_type_book_depr_asset_type
    FOREIGN KEY (asset_type_id)
    REFERENCES ods.asset_types(asset_type_id);

ALTER TABLE ods.asset_type_book_depreciation_settings
    ADD CONSTRAINT fk_asset_type_book_depr_organisation
    FOREIGN KEY (organisation_id)
    REFERENCES ods.organisations(organisation_id);

/* --- Indexes ------------------------------------------------- */
CREATE INDEX IF NOT EXISTS idx_asset_type_book_depr_asset_type_current
    ON ods.asset_type_book_depreciation_settings(asset_type_id)
    WHERE is_current;
CREATE INDEX IF NOT EXISTS idx_asset_type_book_depr_valid_to
    ON ods.asset_type_book_depreciation_settings(valid_to);
CREATE INDEX IF NOT EXISTS idx_asset_type_book_depr_is_current
    ON ods.asset_type_book_depreciation_settings(is_current);
CREATE INDEX IF NOT EXISTS idx_asset_type_book_depr_fetched_at
    ON ods.asset_type_book_depreciation_settings(fetched_at);
CREATE INDEX IF NOT EXISTS idx_asset_type_book_depr_batch_id
    ON ods.asset_type_book_depreciation_settings(batch_id);
CREATE INDEX IF NOT EXISTS idx_asset_type_book_depr_org_id
    ON ods.asset_type_book_depreciation_settings(organisation_id);

/* --- Trigger to maintain row_updated_at ---------------------- */
CREATE TRIGGER trg_update_asset_type_book_depr_row_updated_at
BEFORE UPDATE ON ods.asset_type_book_depreciation_settings
FOR EACH ROW EXECUTE FUNCTION ods.fn_update_row_updated_at();

/* --- Documentation ------------------------------------------ */
COMMENT ON TABLE ods.asset_type_book_depreciation_settings
  IS 'Per‑book depreciation settings (ACCOUNTING or TAX) defined at the asset‑type level; stored as a Type‑2 SCD to capture historical changes.';
COMMENT ON COLUMN ods.asset_type_book_depreciation_settings.book_type
  IS 'Indicates which depreciation book the settings apply to: ACCOUNTING or TAX.';
