-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero AssetTypes
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses BIGINT IDENTITY (PostgreSQL‑preferred).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Business key: asset_type_id (UUID).
--    * Child table asset_type_book_depreciation_settings is optional – create on request.
-- =============================================================

/* -------------------------------------------------------------
   ods.asset_types – Type‑2 SCD for fixed‑asset type catalogue
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.asset_types (
    /* --- Natural / business key ----------------------------- */
    asset_type_id                           UUID            NOT NULL,  -- Xero AssetTypeID

    /* --- Core attributes from schema ------------------------ */
    name                                    VARCHAR(255)    NOT NULL,
    fixed_asset_account_id                  UUID,
    depreciation_expense_account_id         UUID,
    accumulated_depreciation_account_id     UUID,
    depreciation_rate                       NUMERIC(7,4)    CHECK (depreciation_rate >= 0),
    depreciation_method                     VARCHAR(30)     CHECK (depreciation_method IN ('STRAIGHT_LINE','DIMINISHING_VALUE','NONE')),
    averaging_method                        VARCHAR(15)     CHECK (averaging_method IN ('FULL_MONTH','DAILY','NONE')),
    depreciation_calculation_method         VARCHAR(10)     CHECK (depreciation_calculation_method IN ('RATE','LIFE')),
    asset_type_status                       VARCHAR(10)     CHECK (asset_type_status IN ('ACTIVE','ARCHIVED')),
    can_delete                              BOOLEAN,
    created_date_utc                        TIMESTAMPTZ,
    updated_date_utc                        TIMESTAMPTZ,

    /* --- Tenant link --------------------------------------- */
    organisation_id                         UUID            NOT NULL,

    /* --- SCD‑2 infrastructure ------------------------------- */
    surrogate_key               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from                  TIMESTAMPTZ NOT NULL,
    valid_to                    TIMESTAMPTZ NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current                  BOOLEAN NOT NULL DEFAULT TRUE,

    /* --- Audit & status ------------------------------------ */
    fetched_at                  TIMESTAMPTZ NOT NULL,
    row_created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status               ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking --------------------------- */
    batch_id                    UUID            NOT NULL,
    landing_table_name          VARCHAR(255)    NOT NULL,
    landing_record_identifier   VARCHAR(512)    NOT NULL,
    raw_table_name              VARCHAR(255),
    api_call_id                 UUID,
    source_system_id            VARCHAR(100),
    source_record_modified_at   TIMESTAMPTZ,

    /* --- Constraints --------------------------------------- */
    CONSTRAINT uq_asset_types_business_key_current
        UNIQUE (asset_type_id, is_current) WHERE is_current,

    CONSTRAINT ck_asset_types_valid_dates
        CHECK (valid_from < valid_to),

    CONSTRAINT ck_asset_types_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED'))
);

/* --- Foreign Keys ------------------------------------------- */
ALTER TABLE ods.asset_types
    ADD CONSTRAINT fk_asset_types_organisation
    FOREIGN KEY (organisation_id)
    REFERENCES ods.organisations(organisation_id);

ALTER TABLE ods.asset_types
    ADD CONSTRAINT fk_asset_types_fixed_asset_account
    FOREIGN KEY (fixed_asset_account_id)
    REFERENCES ods.accounts(account_id);

ALTER TABLE ods.asset_types
    ADD CONSTRAINT fk_asset_types_depr_exp_account
    FOREIGN KEY (depreciation_expense_account_id)
    REFERENCES ods.accounts(account_id);

ALTER TABLE ods.asset_types
    ADD CONSTRAINT fk_asset_types_accum_depr_account
    FOREIGN KEY (accumulated_depreciation_account_id)
    REFERENCES ods.accounts(account_id);

/* --- Indexes ------------------------------------------------- */
CREATE INDEX IF NOT EXISTS idx_asset_types_business_key_current
        ON ods.asset_types(asset_type_id) WHERE is_current;
CREATE INDEX IF NOT EXISTS idx_asset_types_valid_to
        ON ods.asset_types(valid_to);
CREATE INDEX IF NOT EXISTS idx_asset_types_is_current
        ON ods.asset_types(is_current);
CREATE INDEX IF NOT EXISTS idx_asset_types_fetched_at
        ON ods.asset_types(fetched_at);
CREATE INDEX IF NOT EXISTS idx_asset_types_batch_id
        ON ods.asset_types(batch_id);
CREATE INDEX IF NOT EXISTS idx_asset_types_organisation_id
        ON ods.asset_types(organisation_id);

/* --- Trigger to maintain row_updated_at ---------------------- */
CREATE TRIGGER trg_update_asset_types_row_updated_at
BEFORE UPDATE ON ods.asset_types
FOR EACH ROW EXECUTE FUNCTION ods.fn_update_row_updated_at();

/* --- Documentation ------------------------------------------ */
COMMENT ON TABLE ods.asset_types IS 'Catalogue of fixed‑asset types for an organisation, stored as a Type‑2 slowly‑changing dimension.';
COMMENT ON COLUMN ods.asset_types.asset_type_id IS 'Primary business key from Xero AssetTypeID.';
COMMENT ON COLUMN ods.asset_types.name IS 'Name of the asset type.';
COMMENT ON COLUMN ods.asset_types.depreciation_method IS 'Depreciation method: STRAIGHT_LINE | DIMINISHING_VALUE | NONE.';
