-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero AssetTrackingItems
--  Generated: 28‑May‑2025
--  Notes:
--    * One row per tracking option applied to an asset (max two per asset, per Xero rules).
--    * Composite business key: asset_id + tracking_option_id.
--    * Surrogate key uses BIGINT IDENTITY (preferred over SERIAL).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
-- =============================================================

/* -------------------------------------------------------------
   ods.asset_tracking_items – Type‑2 SCD for Asset → Tracking Option links
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.asset_tracking_items (
    /* --- Composite natural key -------------------------------- */
    asset_id                    UUID            NOT NULL,   -- Parent asset
    tracking_option_id          UUID            NOT NULL,   -- Xero TrackingOptionID

    /* --- Additional attributes -------------------------------- */
    tracking_category_id        UUID            NOT NULL,   -- Category to which the option belongs
    tracking_category_name      VARCHAR(100),               -- Denormalised for convenience
    tracking_option_name        VARCHAR(100),               -- Denormalised for convenience

    /* --- Parent / tenancy link -------------------------------- */
    organisation_id             UUID            NOT NULL,

    /* --- SCD‑2 infrastructure -------------------------------- */
    surrogate_key               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from                  TIMESTAMPTZ NOT NULL,
    valid_to                    TIMESTAMPTZ NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current                  BOOLEAN NOT NULL DEFAULT TRUE,

    /* --- Audit & status -------------------------------------- */
    fetched_at                  TIMESTAMPTZ NOT NULL,
    row_created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status               ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking ----------------------------- */
    batch_id                    UUID            NOT NULL,
    landing_table_name          VARCHAR(255)    NOT NULL,
    landing_record_identifier   VARCHAR(512)    NOT NULL,
    raw_table_name              VARCHAR(255),
    api_call_id                 UUID,
    source_system_id            VARCHAR(100),
    source_record_modified_at   TIMESTAMPTZ,

    /* --- Constraints ----------------------------------------- */
    CONSTRAINT uq_asset_tracking_items_business_key_current
        UNIQUE (asset_id, tracking_option_id, is_current) WHERE is_current,

    CONSTRAINT ck_asset_tracking_items_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),
    CONSTRAINT ck_asset_tracking_items_valid_dates
        CHECK (valid_from < valid_to)
);

/* --- Foreign Keys ------------------------------------------- */
ALTER TABLE ods.asset_tracking_items
    ADD CONSTRAINT fk_asset_tracking_items_asset
    FOREIGN KEY (asset_id)
    REFERENCES ods.assets(asset_id);

ALTER TABLE ods.asset_tracking_items
    ADD CONSTRAINT fk_asset_tracking_items_option
    FOREIGN KEY (tracking_option_id)
    REFERENCES ods.tracking_options(tracking_option_id);

ALTER TABLE ods.asset_tracking_items
    ADD CONSTRAINT fk_asset_tracking_items_organisation
    FOREIGN KEY (organisation_id)
    REFERENCES ods.organisations(organisation_id);

/* --- Indexes ------------------------------------------------- */
CREATE INDEX IF NOT EXISTS idx_asset_tracking_items_business_key_current
        ON ods.asset_tracking_items(asset_id, tracking_option_id) WHERE is_current;
CREATE INDEX IF NOT EXISTS idx_asset_tracking_items_valid_to
        ON ods.asset_tracking_items(valid_to);
CREATE INDEX IF NOT EXISTS idx_asset_tracking_items_is_current
        ON ods.asset_tracking_items(is_current);
CREATE INDEX IF NOT EXISTS idx_asset_tracking_items_fetched_at
        ON ods.asset_tracking_items(fetched_at);
CREATE INDEX IF NOT EXISTS idx_asset_tracking_items_batch_id
        ON ods.asset_tracking_items(batch_id);
CREATE INDEX IF NOT EXISTS idx_asset_tracking_items_organisation_id
        ON ods.asset_tracking_items(organisation_id);

/* --- Trigger to maintain row_updated_at ---------------------- */
CREATE TRIGGER trg_update_asset_tracking_items_row_updated_at
BEFORE UPDATE ON ods.asset_tracking_items
FOR EACH ROW EXECUTE FUNCTION ods.fn_update_row_updated_at();

/* --- Documentation ------------------------------------------ */
COMMENT ON TABLE ods.asset_tracking_items IS 'Links Xero fixed assets to their applied tracking options (up to two per asset) as a Type‑2 dimension.';
COMMENT ON COLUMN ods.asset_tracking_items.asset_id IS 'Parent asset (business key)';
COMMENT ON COLUMN ods.asset_tracking_items.tracking_option_id IS 'Tracking option applied to the asset';
COMMENT ON COLUMN ods.asset_tracking_items.tracking_category_id IS 'Category to which the option belongs.';
