-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero BudgetPeriods
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses BIGINT IDENTITY (PostgreSQL‑preferred).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Composite business key: budget_id + account_id + period_number (one row per month‑per‑account).
-- =============================================================

/* -------------------------------------------------------------
   ods.budget_periods – Type‑2 Slowly Changing Dimensions table
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.budget_periods (
    /* --- Business / natural key ----------------------------- */
    budget_id            UUID            NOT NULL,   -- Parent budget
    account_id           UUID            NOT NULL,   -- Account to which this period amount relates
    period_number        INTEGER         NOT NULL CHECK (period_number BETWEEN 1 AND 24), -- 1 = first month of budget

    /* --- Tenant / organisation ------------------------------ */
    organisation_id      UUID            NOT NULL,

    /* --- Core scalar attributes ----------------------------- */
    period_start_date    DATE            NOT NULL,  -- First day of the accounting period
    amount               NUMERIC(18,2)   NOT NULL CHECK (amount >= 0),

    /* --- SCD‑2 infrastructure ------------------------------- */
    surrogate_key        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from           TIMESTAMPTZ NOT NULL,
    valid_to             TIMESTAMPTZ NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current           BOOLEAN     NOT NULL DEFAULT TRUE,

    /* --- Audit & status ------------------------------------- */
    fetched_at           TIMESTAMPTZ NOT NULL,
    row_created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status        ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking ---------------------------- */
    batch_id                     UUID         NOT NULL,
    landing_table_name           VARCHAR(255) NOT NULL,
    landing_record_identifier    VARCHAR(512) NOT NULL,
    raw_table_name               VARCHAR(255),
    api_call_id                  UUID,
    source_system_id             VARCHAR(100),
    source_record_modified_at    TIMESTAMPTZ,

    /* --- Constraints ---------------------------------------- */
    CONSTRAINT uq_budget_periods_business_key_current
        UNIQUE (budget_id, account_id, period_number, is_current)
        WHERE is_current,

    CONSTRAINT ck_budget_periods_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),

    CONSTRAINT ck_budget_periods_valid_dates
        CHECK (valid_from < valid_to),

    /* --- Foreign Keys --------------------------------------- */
    CONSTRAINT fk_budget_periods_budget
        FOREIGN KEY (budget_id)
        REFERENCES ods.budgets(budget_id) DEFERRABLE INITIALLY DEFERRED,

    CONSTRAINT fk_budget_periods_account
        FOREIGN KEY (account_id)
        REFERENCES ods.accounts(account_id) DEFERRABLE INITIALLY DEFERRED,

    CONSTRAINT fk_budget_periods_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES ods.organisations(organisation_id)
);

/* --- Indexes -------------------------------------------------- */
CREATE INDEX IF NOT EXISTS idx_budget_periods_business_key_current
    ON ods.budget_periods(budget_id, account_id, period_number) WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_budget_periods_valid_to
    ON ods.budget_periods(valid_to);

CREATE INDEX IF NOT EXISTS idx_budget_periods_is_current
    ON ods.budget_periods(is_current);

CREATE INDEX IF NOT EXISTS idx_budget_periods_fetched_at
    ON ods.budget_periods(fetched_at);

CREATE INDEX IF NOT EXISTS idx_budget_periods_batch_id
    ON ods.budget_periods(batch_id);

CREATE INDEX IF NOT EXISTS idx_budget_periods_organisation_id
    ON ods.budget_periods(organisation_id);

/* --- Trigger to maintain row_updated_at --------------------- */
CREATE TRIGGER trg_update_budget_periods_row_updated_at
BEFORE UPDATE ON ods.budget_periods
FOR EACH ROW EXECUTE FUNCTION ods.fn_update_row_updated_at();

/* --- Documentation ----------------------------------------- */
COMMENT ON TABLE ods.budget_periods IS 'Monthly budget amounts per account, linked to a parent budget, stored as Type‑2 slowly changing dimensions.';
COMMENT ON COLUMN ods.budget_periods.period_number IS '1‑based index of the month within the parent budget (max 24).';
COMMENT ON COLUMN ods.budget_periods.amount IS 'Budgeted amount for the period in the organisations base currency.';
COMMENT ON COLUMN ods.budget_periods.is_current IS 'TRUE if this row represents the latest version of the period record.';
