-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero CreditNoteLineItems
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses IDENTITY (PostgreSQL‑preferred over SERIAL).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Business key: line_item_id (UUID).
--    * Parent linkage via credit_note_id + organisation_id; FK to ods.credit_notes.
--    * Tracking and tax components arrays not expanded here – request if separate SCD‑2 tables are needed.
-- =============================================================

/* -------------------------------------------------------------
   ods.credit_note_line_items – line‑level details for credit notes
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.credit_note_line_items (
    /* --- Business / natural key ----------------------------- */
    line_item_id          UUID            NOT NULL, -- Xero LineItemID

    /* --- Relationship keys ---------------------------------- */
    credit_note_id        UUID            NOT NULL,
    organisation_id       UUID            NOT NULL,

    /* --- Core scalar attributes ----------------------------- */
    item_code             VARCHAR(30),
    description           VARCHAR(4000),
    quantity              NUMERIC(18,2),
    unit_amount           NUMERIC(18,2),
    discount_rate         NUMERIC(5,2),       -- percentage 0‑100
    discount_amount       NUMERIC(18,2),
    tax_type              VARCHAR(50),
    tax_amount            NUMERIC(18,2),
    line_amount           NUMERIC(18,2),
    account_code          VARCHAR(10),
    tracking_category_id  UUID,
    tracking_option_id    UUID,

    /* --- SCD‑2 infrastructure ------------------------------- */
    surrogate_key         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from            TIMESTAMPTZ     NOT NULL,
    valid_to              TIMESTAMPTZ     NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current            BOOLEAN         NOT NULL DEFAULT TRUE,

    /* --- Audit & status ------------------------------------- */
    fetched_at            TIMESTAMPTZ     NOT NULL,
    row_created_at        TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at        TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status         ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking ---------------------------- */
    batch_id                  UUID         NOT NULL,
    landing_table_name        VARCHAR(255) NOT NULL,
    landing_record_identifier VARCHAR(512) NOT NULL,
    raw_table_name            VARCHAR(255),
    api_call_id               UUID,
    source_system_id          VARCHAR(100),
    source_record_modified_at TIMESTAMPTZ,

    /* --- Constraints ---------------------------------------- */
    CONSTRAINT uq_credit_note_line_items_business_key_current
        UNIQUE (line_item_id, is_current) WHERE is_current,

    CONSTRAINT fk_credit_note_line_items_credit_note
        FOREIGN KEY (credit_note_id)
        REFERENCES ods.credit_notes(credit_note_id),

    CONSTRAINT fk_credit_note_line_items_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES ods.organisations(organisation_id),

    /* Value checks */
    CONSTRAINT ck_credit_note_line_items_discount_rate
        CHECK (discount_rate IS NULL OR (discount_rate >= 0 AND discount_rate <= 100)),

    CONSTRAINT ck_credit_note_line_items_amounts_non_negative
        CHECK (
            quantity       IS NULL OR quantity       >= 0 AND
            unit_amount    IS NULL OR unit_amount    >= 0 AND
            discount_amount IS NULL OR discount_amount >= 0 AND
            tax_amount     IS NULL OR tax_amount     >= 0 AND
            line_amount    IS NULL OR line_amount    >= 0
        ),

    CONSTRAINT ck_credit_note_line_items_account_code
        CHECK (account_code IS NULL OR account_code ~ '^[A-Z0-9]{1,10}$'),

    CONSTRAINT ck_credit_note_line_items_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),

    CONSTRAINT ck_credit_note_line_items_valid_dates
        CHECK (valid_from < valid_to)
);

/* --- Indexes ------------------------------------------------ */
CREATE INDEX IF NOT EXISTS idx_cn_line_items_business_key_current
    ON ods.credit_note_line_items(line_item_id) WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_cn_line_items_credit_note
    ON ods.credit_note_line_items(credit_note_id);

CREATE INDEX IF NOT EXISTS idx_cn_line_items_valid_to
    ON ods.credit_note_line_items(valid_to);

CREATE INDEX IF NOT EXISTS idx_cn_line_items_is_current
    ON ods.credit_note_line_items(is_current);

CREATE INDEX IF NOT EXISTS idx_cn_line_items_fetched_at
    ON ods.credit_note_line_items(fetched_at);

CREATE INDEX IF NOT EXISTS idx_cn_line_items_batch_id
    ON ods.credit_note_line_items(batch_id);

CREATE INDEX IF NOT EXISTS idx_cn_line_items_organisation_id
    ON ods.credit_note_line_items(organisation_id);

/* --- Trigger to maintain row_updated_at -------------------- */
CREATE TRIGGER trg_update_cn_line_items_row_updated_at
BEFORE UPDATE ON ods.credit_note_line_items
FOR EACH ROW EXECUTE FUNCTION fn_update_row_updated_at();

/* --- Documentation ----------------------------------------- */
COMMENT ON TABLE ods.credit_note_line_items IS 'Line‑level details for credit notes captured as Type‑2 slowly‑changing dimensions (one row per LineItemID version).';
COMMENT ON COLUMN ods.credit_note_line_items.line_item_id IS 'Xero LineItemID (business key).';
COMMENT ON COLUMN ods.credit_note_line_items.credit_note_id IS 'Parent CreditNoteID.';
COMMENT ON COLUMN ods.credit_note_line_items.description IS 'Line item description text.';
COMMENT ON COLUMN ods.credit_note_line_items.surrogate_key IS 'Surrogate identifier for each version of the line item.';
COMMENT ON COLUMN ods.credit_note_line_items.valid_from IS 'Timestamp when this line item version becomes valid.';
COMMENT ON COLUMN ods.credit_note_line_items.valid_to IS 'Timestamp when this line item version ceases to be valid.';
COMMENT ON COLUMN ods.credit_note_line_items.is_current IS 'TRUE if this row represents the current version.';
