-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero CreditNoteAllocations
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses IDENTITY (PostgreSQL‑preferred).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Business key: allocation_id (UUID). One allocation per row.
--    * Parent linkage via credit_note_id + organisation_id. Optional invoice_id link.
-- =============================================================

/* -------------------------------------------------------------
   ods.credit_note_allocations – credit applied from a credit note
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.credit_note_allocations (
    /* --- Business / natural key ----------------------------- */
    allocation_id        UUID            NOT NULL, -- Xero AllocationID

    /* --- Relationship keys ---------------------------------- */
    credit_note_id       UUID            NOT NULL,
    organisation_id      UUID            NOT NULL,
    invoice_id           UUID,

    /* --- Core scalar attributes ----------------------------- */
    date                 TIMESTAMPTZ,
    amount               NUMERIC(18,2),

    /* --- SCD‑2 infrastructure ------------------------------- */
    surrogate_key        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from           TIMESTAMPTZ     NOT NULL,
    valid_to             TIMESTAMPTZ     NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current           BOOLEAN         NOT NULL DEFAULT TRUE,

    /* --- Audit & status ------------------------------------- */
    fetched_at           TIMESTAMPTZ     NOT NULL,
    row_created_at       TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at       TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status        ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking ---------------------------- */
    batch_id                  UUID         NOT NULL,
    landing_table_name        VARCHAR(255) NOT NULL,
    landing_record_identifier VARCHAR(512) NOT NULL,
    raw_table_name            VARCHAR(255),
    api_call_id               UUID,
    source_system_id          VARCHAR(100),
    source_record_modified_at TIMESTAMPTZ,

    /* --- Constraints ---------------------------------------- */
    CONSTRAINT uq_credit_note_allocations_business_key_current
        UNIQUE (allocation_id, is_current) WHERE is_current,

    CONSTRAINT fk_credit_note_allocations_credit_note
        FOREIGN KEY (credit_note_id)
        REFERENCES ods.credit_notes(credit_note_id),

    CONSTRAINT fk_credit_note_allocations_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES ods.organisations(organisation_id),

    CONSTRAINT fk_credit_note_allocations_invoice
        FOREIGN KEY (invoice_id)
        REFERENCES ods.invoices(invoice_id),

    /* Value checks */
    CONSTRAINT ck_credit_note_allocations_amount_non_negative
        CHECK (amount IS NULL OR amount >= 0),

    CONSTRAINT ck_credit_note_allocations_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),

    CONSTRAINT ck_credit_note_allocations_valid_dates
        CHECK (valid_from < valid_to)
);

/* --- Indexes ------------------------------------------------ */
CREATE INDEX IF NOT EXISTS idx_cn_allocations_business_key_current
    ON ods.credit_note_allocations(allocation_id) WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_cn_allocations_credit_note
    ON ods.credit_note_allocations(credit_note_id);

CREATE INDEX IF NOT EXISTS idx_cn_allocations_invoice
    ON ods.credit_note_allocations(invoice_id);

CREATE INDEX IF NOT EXISTS idx_cn_allocations_valid_to
    ON ods.credit_note_allocations(valid_to);

CREATE INDEX IF NOT EXISTS idx_cn_allocations_is_current
    ON ods.credit_note_allocations(is_current);

CREATE INDEX IF NOT EXISTS idx_cn_allocations_fetched_at
    ON ods.credit_note_allocations(fetched_at);

CREATE INDEX IF NOT EXISTS idx_cn_allocations_batch_id
    ON ods.credit_note_allocations(batch_id);

CREATE INDEX IF NOT EXISTS idx_cn_allocations_organisation_id
    ON ods.credit_note_allocations(organisation_id);

/* --- Trigger to maintain row_updated_at -------------------- */
CREATE TRIGGER trg_update_cn_allocations_row_updated_at
BEFORE UPDATE ON ods.credit_note_allocations
FOR EACH ROW EXECUTE FUNCTION ods.fn_update_row_updated_at();

/* --- Documentation ----------------------------------------- */
COMMENT ON TABLE ods.credit_note_allocations IS 'Allocations of credit notes against invoices or bills, captured as Type‑2 slowly‑changing dimensions.';
COMMENT ON COLUMN ods.credit_note_allocations.allocation_id IS 'Xero AllocationID (business key).';
COMMENT ON COLUMN ods.credit_note_allocations.credit_note_id IS 'Parent CreditNoteID to which this allocation applies.';
COMMENT ON COLUMN ods.credit_note_allocations.invoice_id IS 'InvoiceID or BillID the credit note is applied to (nullable).';
COMMENT ON COLUMN ods.credit_note_allocations.amount IS 'Allocation amount in document currency.';
COMMENT ON COLUMN ods.credit_note_allocations.surrogate_key IS 'Surrogate identifier for each version of the allocation record.';
COMMENT ON COLUMN ods.credit_note_allocations.valid_from IS 'Timestamp when this allocation record version becomes valid.';
COMMENT ON COLUMN ods.credit_note_allocations.valid_to IS 'Timestamp when this allocation record version ceases to be valid.';
COMMENT ON COLUMN ods.credit_note_allocations.is_current IS 'TRUE if this row represents the current version.';
