-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero CreditNoteAttachments
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses BIGINT IDENTITY (PostgreSQL‑preferred).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Composite business key: credit_note_id + attachment_id (one attachment per credit note).
-- =============================================================

/* -------------------------------------------------------------
   ods.credit_note_attachments – file attachments linked to credit notes
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.credit_note_attachments (
    /* --- Business / natural key ----------------------------- */
    attachment_id       UUID            NOT NULL, -- Xero AttachmentID

    /* --- Relationship keys ---------------------------------- */
    credit_note_id      UUID            NOT NULL,
    organisation_id     UUID            NOT NULL,

    /* --- Core scalar attributes ----------------------------- */
    file_name           VARCHAR(255),
    url                 VARCHAR(2048),
    mime_type           VARCHAR(100),
    content_length      BIGINT,
    include_online      BOOLEAN,
    updated_date_utc    TIMESTAMPTZ,

    /* --- SCD‑2 infrastructure ------------------------------- */
    surrogate_key       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from          TIMESTAMPTZ     NOT NULL,
    valid_to            TIMESTAMPTZ     NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current          BOOLEAN         NOT NULL DEFAULT TRUE,

    /* --- Audit & status ------------------------------------- */
    fetched_at          TIMESTAMPTZ     NOT NULL,
    row_created_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status       ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking ---------------------------- */
    batch_id                  UUID         NOT NULL,
    landing_table_name        VARCHAR(255) NOT NULL,
    landing_record_identifier VARCHAR(512) NOT NULL,
    raw_table_name            VARCHAR(255),
    api_call_id               UUID,
    source_system_id          VARCHAR(100),
    source_record_modified_at TIMESTAMPTZ,

    /* --- Constraints ---------------------------------------- */
    CONSTRAINT uq_cn_attachments_business_key_current
        UNIQUE (credit_note_id, attachment_id, is_current) WHERE is_current,

    CONSTRAINT fk_cn_attachments_credit_note
        FOREIGN KEY (credit_note_id)
        REFERENCES ods.credit_notes(credit_note_id),

    CONSTRAINT fk_cn_attachments_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES ods.organisations(organisation_id),

    /* Value checks */
    CONSTRAINT ck_cn_attachments_content_length_non_negative
        CHECK (content_length IS NULL OR content_length >= 0),

    CONSTRAINT ck_cn_attachments_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),

    CONSTRAINT ck_cn_attachments_valid_dates
        CHECK (valid_from < valid_to)
);

/* --- Indexes ------------------------------------------------ */
CREATE INDEX IF NOT EXISTS idx_cn_attachments_business_key_current
    ON ods.credit_note_attachments(credit_note_id, attachment_id) WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_cn_attachments_credit_note
    ON ods.credit_note_attachments(credit_note_id);

CREATE INDEX IF NOT EXISTS idx_cn_attachments_valid_to
    ON ods.credit_note_attachments(valid_to);

CREATE INDEX IF NOT EXISTS idx_cn_attachments_is_current
    ON ods.credit_note_attachments(is_current);

CREATE INDEX IF NOT EXISTS idx_cn_attachments_fetched_at
    ON ods.credit_note_attachments(fetched_at);

CREATE INDEX IF NOT EXISTS idx_cn_attachments_batch_id
    ON ods.credit_note_attachments(batch_id);

CREATE INDEX IF NOT EXISTS idx_cn_attachments_organisation_id
    ON ods.credit_note_attachments(organisation_id);

/* --- Trigger to maintain row_updated_at -------------------- */
CREATE TRIGGER trg_update_cn_attachments_row_updated_at
BEFORE UPDATE ON ods.credit_note_attachments
FOR EACH ROW EXECUTE FUNCTION ods.fn_update_row_updated_at();

/* --- Documentation ----------------------------------------- */
COMMENT ON TABLE ods.credit_note_attachments IS 'Attachments linked to Xero credit notes, captured as Type‑2 slowly‑changing dimensions.';
COMMENT ON COLUMN ods.credit_note_attachments.attachment_id IS 'Xero AttachmentID (business key).';
COMMENT ON COLUMN ods.credit_note_attachments.credit_note_id IS 'Parent CreditNoteID this attachment belongs to.';
COMMENT ON COLUMN ods.credit_note_attachments.file_name IS 'Original file name of the attachment.';
COMMENT ON COLUMN ods.credit_note_attachments.url IS 'API‑accessible URL for the attachment.';
COMMENT ON COLUMN ods.credit_note_attachments.mime_type IS 'MIME type reported by Xero.';
COMMENT ON COLUMN ods.credit_note_attachments.content_length IS 'Size of the attachment in bytes.';
COMMENT ON COLUMN ods.credit_note_attachments.include_online IS 'TRUE if the file should be included in online invoices.';
COMMENT ON COLUMN ods.credit_note_attachments.surrogate_key IS 'Surrogate identifier for each version of the attachment record.';
COMMENT ON COLUMN ods.credit_note_attachments.valid_from IS 'Timestamp when this attachment record version becomes valid.';
COMMENT ON COLUMN ods.credit_note_attachments.valid_to IS 'Timestamp when this attachment record version ceases to be valid.';
COMMENT ON COLUMN ods.credit_note_attachments.is_current IS 'TRUE if this row represents the current version.';
