-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero Currencies
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses IDENTITY (PostgreSQL‑preferred).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Business key: organisation_id + code (3‑letter ISO currency code).
--    * Enforces code format with CHECK (^[A‑Z]{3}$).
-- =============================================================

/* -------------------------------------------------------------
   ods.currencies – list of currencies enabled for each organisation
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.currencies (
    /* --- Business / natural keys ----------------------------- */
    organisation_id UUID         NOT NULL,   -- Tenant / organisation
    code            VARCHAR(3)   NOT NULL,   -- ISO 4217 currency code

    /* --- Core scalar attributes from Currency schema --------- */
    description     VARCHAR(255),            -- Name of the currency

    /* --- SCD‑2 infrastructure -------------------------------- */
    surrogate_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from    TIMESTAMPTZ NOT NULL,
    valid_to      TIMESTAMPTZ NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current    BOOLEAN     NOT NULL DEFAULT TRUE,

    /* --- Audit & status -------------------------------------- */
    fetched_at     TIMESTAMPTZ NOT NULL,
    row_created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status  ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking ----------------------------- */
    batch_id                  UUID         NOT NULL,
    landing_table_name        VARCHAR(255) NOT NULL,
    landing_record_identifier VARCHAR(512) NOT NULL,
    raw_table_name            VARCHAR(255),
    api_call_id               UUID,
    source_system_id          VARCHAR(100),
    source_record_modified_at TIMESTAMPTZ,

    /* --- Constraints ----------------------------------------- */
    CONSTRAINT uq_currencies_business_key_current
        UNIQUE (organisation_id, code, is_current)
        WHERE is_current,

    CONSTRAINT fk_currencies_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES ods.organisations(organisation_id),

    /* enumerations / format checks ---------------------------- */
    CONSTRAINT ck_currencies_code_format
        CHECK (code ~ '^[A-Z]{3}$'),

    /* generic checks ------------------------------------------ */
    CONSTRAINT ck_currencies_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),

    CONSTRAINT ck_currencies_valid_dates
        CHECK (valid_from < valid_to)
);

/* --- Indexes -------------------------------------------------- */
CREATE INDEX IF NOT EXISTS idx_currencies_business_key_current
    ON ods.currencies(organisation_id, code) WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_currencies_valid_to
    ON ods.currencies(valid_to);

CREATE INDEX IF NOT EXISTS idx_currencies_is_current
    ON ods.currencies(is_current);

CREATE INDEX IF NOT EXISTS idx_currencies_fetched_at
    ON ods.currencies(fetched_at);

CREATE INDEX IF NOT EXISTS idx_currencies_batch_id
    ON ods.currencies(batch_id);

CREATE INDEX IF NOT EXISTS idx_currencies_org_id
    ON ods.currencies(organisation_id);

/* --- Trigger to maintain row_updated_at ----------------------- */
CREATE TRIGGER trg_update_currencies_row_updated_at
BEFORE UPDATE ON ods.currencies
FOR EACH ROW EXECUTE FUNCTION fn_update_row_updated_at();

/* --- Documentation ------------------------------------------- */
COMMENT ON TABLE ods.currencies IS 'Currencies enabled for each Xero organisation, stored as a Type‑2 Slowly Changing Dimension.';
COMMENT ON COLUMN ods.currencies.organisation_id IS 'Tenant foreign‑key – identifies the organisation to which the currency belongs.';
COMMENT ON COLUMN ods.currencies.code IS 'ISO 4217 three‑letter currency code (business key).';
COMMENT ON COLUMN ods.currencies.surrogate_key IS 'Surrogate key for each version of the currency record.';
COMMENT ON COLUMN ods.currencies.valid_from IS 'Timestamp at which this version becomes valid.';
COMMENT ON COLUMN ods.currencies.valid_to IS 'Timestamp at which this version ceases to be valid.';
COMMENT ON COLUMN ods.currencies.is_current IS 'TRUE if this row is the current version.';
