-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero InvoiceLineItems
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses IDENTITY (PostgreSQL‑preferred).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Business key: line_item_id (UUID).
--    * Parent linkage via invoice_id + organisation_id; FK to invoices.
--    * Tracking array not expanded here – request if a separate table is desired.
-- =============================================================

/* -------------------------------------------------------------
   ods.invoice_line_items – line‑level details for each invoice (Type‑2 SCD)
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.invoice_line_items (
    /* --- Business / natural key ----------------------------- */
    line_item_id        UUID           NOT NULL, -- Xero LineItemID

    /* --- Parent references ---------------------------------- */
    invoice_id          UUID           NOT NULL,
    organisation_id     UUID           NOT NULL,

    /* --- Core scalar attributes from LineItem schema -------- */
    item_code           VARCHAR(100),
    description         VARCHAR(4000),
    quantity            NUMERIC(18,4),
    unit_amount         NUMERIC(18,6),
    discount_rate       NUMERIC(9,4),  -- percentage 0‑100
    discount_amount     NUMERIC(18,2), -- absolute value
    tax_type            VARCHAR(50),   -- large enum; not constrained here
    tax_amount          NUMERIC(18,2),
    line_amount         NUMERIC(18,2),
    account_code        VARCHAR(10),
    tracking_summary    VARCHAR(255),  -- concatenated tracking values

    /* --- SCD‑2 infrastructure ------------------------------- */
    surrogate_key       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from          TIMESTAMPTZ    NOT NULL,
    valid_to            TIMESTAMPTZ    NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current          BOOLEAN        NOT NULL DEFAULT TRUE,

    /* --- Audit & status ------------------------------------- */
    fetched_at          TIMESTAMPTZ    NOT NULL,
    row_created_at      TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at      TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status       ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking ---------------------------- */
    batch_id                  UUID         NOT NULL,
    landing_table_name        VARCHAR(255) NOT NULL,
    landing_record_identifier VARCHAR(512) NOT NULL,
    raw_table_name            VARCHAR(255),
    api_call_id               UUID,
    source_system_id          VARCHAR(100),
    source_record_modified_at TIMESTAMPTZ,

    /* --- Constraints ---------------------------------------- */
    CONSTRAINT uq_invoice_line_items_business_key_current
        UNIQUE (line_item_id, is_current)
        WHERE is_current,

    CONSTRAINT fk_invoice_line_items_invoice
        FOREIGN KEY (invoice_id)
        REFERENCES ods.invoices(invoice_id),

    CONSTRAINT fk_invoice_line_items_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES ods.organisations(organisation_id),

    -- Value checks
    CONSTRAINT ck_line_items_quantity_non_negative
        CHECK (quantity IS NULL OR quantity >= 0),

    CONSTRAINT ck_line_items_unit_amount_non_negative
        CHECK (unit_amount IS NULL OR unit_amount >= 0),

    CONSTRAINT ck_line_items_discount_rate_range
        CHECK (discount_rate IS NULL OR (discount_rate >= 0 AND discount_rate <= 100)),

    CONSTRAINT ck_line_items_discount_amount_non_negative
        CHECK (discount_amount IS NULL OR discount_amount >= 0),

    CONSTRAINT ck_line_items_tax_amount_non_negative
        CHECK (tax_amount IS NULL OR tax_amount >= 0),

    CONSTRAINT ck_line_items_line_amount_non_negative
        CHECK (line_amount IS NULL OR line_amount >= 0),

    -- Generic SCD & status checks
    CONSTRAINT ck_line_items_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),

    CONSTRAINT ck_line_items_valid_dates
        CHECK (valid_from < valid_to)
);

/* --- Indexes ------------------------------------------------ */
CREATE INDEX IF NOT EXISTS idx_line_items_business_key_current
    ON ods.invoice_line_items(line_item_id)
    WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_line_items_invoice_id
    ON ods.invoice_line_items(invoice_id);

CREATE INDEX IF NOT EXISTS idx_line_items_valid_to
    ON ods.invoice_line_items(valid_to);

CREATE INDEX IF NOT EXISTS idx_line_items_is_current
    ON ods.invoice_line_items(is_current);

CREATE INDEX IF NOT EXISTS idx_line_items_fetched_at
    ON ods.invoice_line_items(fetched_at);

CREATE INDEX IF NOT EXISTS idx_line_items_batch_id
    ON ods.invoice_line_items(batch_id);

CREATE INDEX IF NOT EXISTS idx_line_items_organisation_id
    ON ods.invoice_line_items(organisation_id);

/* --- Trigger to maintain row_updated_at -------------------- */
CREATE TRIGGER trg_update_invoice_line_items_row_updated_at
BEFORE UPDATE ON ods.invoice_line_items
FOR EACH ROW EXECUTE FUNCTION ods.fn_update_row_updated_at();

/* --- Documentation ----------------------------------------- */
COMMENT ON TABLE ods.invoice_line_items IS 'Invoice line‑level details stored as Type‑2 slowly‑changing dimensions (one row per version).';
COMMENT ON COLUMN ods.invoice_line_items.line_item_id IS 'Natural business key (Xero LineItemID).';
COMMENT ON COLUMN ods.invoice_line_items.invoice_id IS 'Parent invoice – FK to ods.invoices(invoice_id).';
COMMENT ON COLUMN ods.invoice_line_items.item_code IS 'Xero ItemCode associated with the line.';
COMMENT ON COLUMN ods.invoice_line_items.quantity IS 'Line quantity.';
COMMENT ON COLUMN ods.invoice_line_items.unit_amount IS 'Unit price before discount & tax.';
COMMENT ON COLUMN ods.invoice_line_items.discount_rate IS 'Percentage discount applied to the line.';
COMMENT ON COLUMN ods.invoice_line_items.discount_amount IS 'Absolute discount applied to the line.';
COMMENT ON COLUMN ods.invoice_line_items.line_amount IS 'Total line amount after discount, before tax.';
COMMENT ON COLUMN ods.invoice_line_items.surrogate_key IS 'Surrogate identifier for each version of the line item record.';
COMMENT ON COLUMN ods.invoice_line_items.valid_from IS 'Timestamp when this line item version becomes valid.';
COMMENT ON COLUMN ods.invoice_line_items.valid_to IS 'Timestamp when this line item version ceases to be valid.';
COMMENT ON COLUMN ods.invoice_line_items.is_current IS 'TRUE if this row represents the current version.';
