-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero JournalLines
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses BIGINT IDENTITY (PostgreSQL‑preferred).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Business key: journal_line_id (UUID).
--    * Parent linkage via journal_id + organisation_id; FK to ods.journals.
--    * TrackingCategories array is NOT expanded here – request an `journal_line_tracking` table if required.
-- =============================================================

/* -------------------------------------------------------------
   ods.journal_lines – Line items within journals, captured as
   Type‑2 SCD records
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.journal_lines (
    /* --- Business / natural key -------------------------------- */
    journal_line_id   UUID            NOT NULL,   -- Xero JournalLineID

    /* --- Relationship keys ------------------------------------- */
    journal_id        UUID            NOT NULL,
    organisation_id   UUID            NOT NULL,

    /* --- Core scalar attributes -------------------------------- */
    account_id        UUID,
    account_code      VARCHAR(10),
    account_type      VARCHAR(20),
    account_name      VARCHAR(150),
    description       VARCHAR(4000),
    net_amount        NUMERIC(18,2)   NOT NULL,
    gross_amount      NUMERIC(18,2)   NOT NULL,
    tax_amount        NUMERIC(18,2),
    tax_type          VARCHAR(50),
    tax_name          VARCHAR(255),

    /* --- SCD‑2 infrastructure ---------------------------------- */
    surrogate_key     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from        TIMESTAMPTZ     NOT NULL,
    valid_to          TIMESTAMPTZ     NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current        BOOLEAN         NOT NULL DEFAULT TRUE,

    /* --- Audit & status ---------------------------------------- */
    fetched_at                   TIMESTAMPTZ NOT NULL,
    row_created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status                ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking ------------------------------- */
    batch_id                     UUID         NOT NULL,
    landing_table_name           VARCHAR(255) NOT NULL,
    landing_record_identifier    VARCHAR(512) NOT NULL,
    raw_table_name               VARCHAR(255),
    api_call_id                  UUID,
    source_system_id             VARCHAR(100),
    source_record_modified_at    TIMESTAMPTZ,

    /* --- Constraints ------------------------------------------- */
    CONSTRAINT uq_journal_lines_business_key_current
        UNIQUE (journal_line_id, is_current) WHERE is_current,

    CONSTRAINT fk_journal_lines_journal
        FOREIGN KEY (journal_id)
        REFERENCES ods.journals(journal_id),

    CONSTRAINT fk_journal_lines_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES ods.organisations(organisation_id),

    CONSTRAINT ck_journal_lines_account_code
        CHECK (account_code IS NULL OR account_code ~ '^[A-Z0-9]{1,10}$'),

    CONSTRAINT ck_journal_lines_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),

    CONSTRAINT ck_journal_lines_valid_dates
        CHECK (valid_from < valid_to)
);

/* --- Indexes -------------------------------------------------- */
CREATE INDEX IF NOT EXISTS idx_journal_lines_business_key_current
    ON ods.journal_lines(journal_line_id) WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_journal_lines_valid_to
    ON ods.journal_lines(valid_to);

CREATE INDEX IF NOT EXISTS idx_journal_lines_is_current
    ON ods.journal_lines(is_current);

CREATE INDEX IF NOT EXISTS idx_journal_lines_fetched_at
    ON ods.journal_lines(fetched_at);

CREATE INDEX IF NOT EXISTS idx_journal_lines_batch_id
    ON ods.journal_lines(batch_id);

CREATE INDEX IF NOT EXISTS idx_journal_lines_journal_id
    ON ods.journal_lines(journal_id);

CREATE INDEX IF NOT EXISTS idx_journal_lines_organisation_id
    ON ods.journal_lines(organisation_id);

/* --- Trigger to maintain row_updated_at ----------------------- */
CREATE TRIGGER trg_update_journal_lines_row_updated_at
BEFORE UPDATE ON ods.journal_lines
FOR EACH ROW EXECUTE FUNCTION fn_update_row_updated_at();

/* --- Documentation ------------------------------------------- */
COMMENT ON TABLE ods.journal_lines IS 'Line items belonging to Xero journals, stored as Type‑2 slowly‑changing dimensions (one row per version).';
COMMENT ON COLUMN ods.journal_lines.journal_line_id IS 'Xero JournalLineID (business key).';
COMMENT ON COLUMN ods.journal_lines.account_code IS 'Xero account code associated with the line item.';
COMMENT ON COLUMN ods.journal_lines.is_current IS 'TRUE if this row represents the current version of the journal line.';
