-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero Journals
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses BIGINT IDENTITY (PostgreSQL‑preferred).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Business key: journal_id (UUID).
--    * Nested array JournalLines NOT expanded here – ask to generate `journal_lines` table if needed.
-- =============================================================

/* -------------------------------------------------------------
   ods.journals – Xero journals captured as Type‑2 SCD records
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.journals (
    /* --- Business / natural key -------------------------------- */
    journal_id        UUID            NOT NULL,   -- Xero JournalID

    /* --- Relationship keys ------------------------------------- */
    organisation_id   UUID            NOT NULL,

    /* --- Core scalar attributes -------------------------------- */
    journal_date      DATE            NOT NULL,
    created_date_utc  TIMESTAMPTZ     NOT NULL,
    journal_number    VARCHAR(20),
    reference         VARCHAR(255),
    source_id         UUID,
    source_type       VARCHAR(20),

    /* --- SCD‑2 infrastructure ---------------------------------- */
    surrogate_key     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from        TIMESTAMPTZ     NOT NULL,
    valid_to          TIMESTAMPTZ     NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current        BOOLEAN         NOT NULL DEFAULT TRUE,

    /* --- Audit & status ---------------------------------------- */
    fetched_at                   TIMESTAMPTZ NOT NULL,
    row_created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status                ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking ------------------------------- */
    batch_id                     UUID         NOT NULL,
    landing_table_name           VARCHAR(255) NOT NULL,
    landing_record_identifier    VARCHAR(512) NOT NULL,
    raw_table_name               VARCHAR(255),
    api_call_id                  UUID,
    source_system_id             VARCHAR(100),
    source_record_modified_at    TIMESTAMPTZ,

    /* --- Constraints ------------------------------------------- */
    CONSTRAINT uq_journals_business_key_current
        UNIQUE (journal_id, is_current) WHERE is_current,

    CONSTRAINT fk_journals_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES ods.organisations(organisation_id),

    CONSTRAINT ck_journals_source_type
        CHECK (source_type IS NULL OR source_type IN (
            'ACCREC','ACCPAY','ACCRECCREDIT','ACCPAYCREDIT','JOURNAL','MANUAL'
        )),

    CONSTRAINT ck_journals_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),

    CONSTRAINT ck_journals_valid_dates
        CHECK (valid_from < valid_to)
);

/* --- Indexes -------------------------------------------------- */
CREATE INDEX IF NOT EXISTS idx_journals_business_key_current
    ON ods.journals(journal_id) WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_journals_valid_to
    ON ods.journals(valid_to);

CREATE INDEX IF NOT EXISTS idx_journals_is_current
    ON ods.journals(is_current);

CREATE INDEX IF NOT EXISTS idx_journals_fetched_at
    ON ods.journals(fetched_at);

CREATE INDEX IF NOT EXISTS idx_journals_batch_id
    ON ods.journals(batch_id);

CREATE INDEX IF NOT EXISTS idx_journals_organisation_id
    ON ods.journals(organisation_id);

/* --- Trigger to maintain row_updated_at ----------------------- */
CREATE TRIGGER trg_update_journals_row_updated_at
BEFORE UPDATE ON ods.journals
FOR EACH ROW EXECUTE FUNCTION fn_update_row_updated_at();

/* --- Documentation ------------------------------------------- */
COMMENT ON TABLE ods.journals IS 'General and manual journals captured from Xero, stored as Type‑2 slowly‑changing dimensions (one row per version).';
COMMENT ON COLUMN ods.journals.journal_id IS 'Xero JournalID (business key).';
COMMENT ON COLUMN ods.journals.source_type IS 'Originating source for the journal (e.g. ACCREC, ACCPAY, MANUAL).';
COMMENT ON COLUMN ods.journals.is_current IS 'TRUE if this row represents the current version of the journal.';
