-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero ManualJournals
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses BIGINT IDENTITY (PostgreSQL‑preferred).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Business key: manual_journal_id (UUID).
--    * JournalLines array is NOT expanded here – request a `manual_journal_lines` table if required.
-- =============================================================

/* -------------------------------------------------------------
   ods.manual_journals – Manual journals captured as SCD‑2 records
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.manual_journals (
    /* --- Business / natural key -------------------------------- */
    manual_journal_id   UUID            NOT NULL,  -- Xero ManualJournalID

    /* --- Relationship keys ------------------------------------- */
    organisation_id     UUID            NOT NULL,

    /* --- Core scalar attributes -------------------------------- */
    status                       VARCHAR(10),           -- DRAFT | POSTED
    line_amount_types            VARCHAR(10),           -- EXCLUSIVE | INCLUSIVE | NOTAX
    journal_date                 DATE,
    created_date_utc             TIMESTAMPTZ,
    narration                    VARCHAR(4000),
    journal_number               INTEGER,
    url                          VARCHAR(255),
    reference                    VARCHAR(255),
    show_on_cash_basis_reports   BOOLEAN,
    has_attachments              BOOLEAN,
    updated_date_utc             TIMESTAMPTZ,

    /* --- SCD‑2 infrastructure ---------------------------------- */
    surrogate_key     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from        TIMESTAMPTZ     NOT NULL,
    valid_to          TIMESTAMPTZ     NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current        BOOLEAN         NOT NULL DEFAULT TRUE,

    /* --- Audit & status ---------------------------------------- */
    fetched_at                   TIMESTAMPTZ NOT NULL,
    row_created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status                ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking ------------------------------- */
    batch_id                     UUID         NOT NULL,
    landing_table_name           VARCHAR(255) NOT NULL,
    landing_record_identifier    VARCHAR(512) NOT NULL,
    raw_table_name               VARCHAR(255),
    api_call_id                  UUID,
    source_system_id             VARCHAR(100),
    source_record_modified_at    TIMESTAMPTZ,

    /* --- Constraints ------------------------------------------- */
    CONSTRAINT uq_manual_journals_business_key_current
        UNIQUE (manual_journal_id, is_current) WHERE is_current,

    CONSTRAINT fk_manual_journals_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES ods.organisations(organisation_id),

    CONSTRAINT ck_manual_journals_status
        CHECK (status IS NULL OR status IN ('DRAFT','POSTED')),

    CONSTRAINT ck_manual_journals_line_amount_types
        CHECK (line_amount_types IS NULL OR line_amount_types IN ('EXCLUSIVE','INCLUSIVE','NOTAX')),

    CONSTRAINT ck_manual_journals_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),

    CONSTRAINT ck_manual_journals_valid_dates
        CHECK (valid_from < valid_to)
);

/* --- Indexes -------------------------------------------------- */
CREATE INDEX IF NOT EXISTS idx_manual_journals_business_key_current
    ON ods.manual_journals(manual_journal_id) WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_manual_journals_valid_to
    ON ods.manual_journals(valid_to);

CREATE INDEX IF NOT EXISTS idx_manual_journals_is_current
    ON ods.manual_journals(is_current);

CREATE INDEX IF NOT EXISTS idx_manual_journals_fetched_at
    ON ods.manual_journals(fetched_at);

CREATE INDEX IF NOT EXISTS idx_manual_journals_batch_id
    ON ods.manual_journals(batch_id);

CREATE INDEX IF NOT EXISTS idx_manual_journals_organisation_id
    ON ods.manual_journals(organisation_id);

/* --- Trigger to maintain row_updated_at ----------------------- */
CREATE TRIGGER trg_update_manual_journals_row_updated_at
BEFORE UPDATE ON ods.manual_journals
FOR EACH ROW EXECUTE FUNCTION fn_update_row_updated_at();

/* --- Documentation ------------------------------------------- */
COMMENT ON TABLE ods.manual_journals IS 'Manual journals stored as Type‑2 slowly‑changing dimensions (one row per version).';
COMMENT ON COLUMN ods.manual_journals.manual_journal_id IS 'Xero ManualJournalID (business key).';
COMMENT ON COLUMN ods.manual_journals.status IS 'Journal status: DRAFT | POSTED.';
COMMENT ON COLUMN ods.manual_journals.line_amount_types IS 'Line amount type: EXCLUSIVE | INCLUSIVE | NOTAX.';
COMMENT ON COLUMN ods.manual_journals.is_current IS 'TRUE if this row represents the current version of the manual journal.';
