-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero OrganisationAddresses
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses IDENTITY.
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Composite natural key: organisation_id + address_type (one address per type per organisation).
-- =============================================================

/* -------------------------------------------------------------
   ods.organisation_addresses – address details for organisations
   ----------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.organisation_addresses (
    /* --- Business / natural key -------------------------------- */
    organisation_id UUID        NOT NULL,
    address_type    VARCHAR(20) NOT NULL,

    /* --- Scalar attributes (AddressForOrganisation schema) ----- */
    address_line1 VARCHAR(500),
    address_line2 VARCHAR(500),
    address_line3 VARCHAR(500),
    address_line4 VARCHAR(500),
    city          VARCHAR(255),
    region        VARCHAR(255),
    postal_code   VARCHAR(50),
    country       VARCHAR(50),
    attention_to  VARCHAR(255),

    /* --- SCD‑2 infrastructure ---------------------------------- */
    surrogate_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from    TIMESTAMPTZ NOT NULL,
    valid_to      TIMESTAMPTZ NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current    BOOLEAN     NOT NULL DEFAULT TRUE,

    /* --- Audit & status ---------------------------------------- */
    fetched_at     TIMESTAMPTZ NOT NULL,
    row_created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status  ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking ------------------------------- */
    batch_id                  UUID         NOT NULL,
    landing_table_name        VARCHAR(255) NOT NULL,
    landing_record_identifier VARCHAR(512) NOT NULL,
    raw_table_name            VARCHAR(255),
    api_call_id               UUID,
    source_system_id          VARCHAR(100),
    source_record_modified_at TIMESTAMPTZ,

    /* --- Constraints ------------------------------------------- */
    CONSTRAINT uq_org_addresses_business_key_current
        UNIQUE (organisation_id, address_type, is_current) WHERE is_current,

    CONSTRAINT fk_org_addresses_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES ods.organisations(organisation_id),

    CONSTRAINT ck_org_addresses_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),

    CONSTRAINT ck_org_addresses_valid_dates
        CHECK (valid_from < valid_to),

    CONSTRAINT ck_org_addresses_type
        CHECK (address_type IN ('STREET','POBOX','DELIVERY'))
);

/* --- Indexes -------------------------------------------------- */
CREATE INDEX IF NOT EXISTS idx_org_addresses_business_key_current
    ON ods.organisation_addresses(organisation_id, address_type) WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_org_addresses_valid_to
    ON ods.organisation_addresses(valid_to);

CREATE INDEX IF NOT EXISTS idx_org_addresses_is_current
    ON ods.organisation_addresses(is_current);

CREATE INDEX IF NOT EXISTS idx_org_addresses_fetched_at
    ON ods.organisation_addresses(fetched_at);

CREATE INDEX IF NOT EXISTS idx_org_addresses_batch_id
    ON ods.organisation_addresses(batch_id);

/* --- Row‑updated‑at trigger ---------------------------------- */
CREATE TRIGGER trg_update_org_addresses_row_updated_at
BEFORE UPDATE ON ods.organisation_addresses
FOR EACH ROW EXECUTE FUNCTION ods.fn_update_row_updated_at();

/* --- Documentation ------------------------------------------- */
COMMENT ON TABLE ods.organisation_addresses IS 'Physical / postal addresses for Xero organisations, captured as a Type‑2 SCD to retain history.';
COMMENT ON COLUMN ods.organisation_addresses.organisation_id IS 'Foreign key to ods.organisations (business key).';
COMMENT ON COLUMN ods.organisation_addresses.address_type IS 'Address type: STREET, POBOX or DELIVERY as per Xero enum.';
COMMENT ON COLUMN ods.organisation_addresses.surrogate_key IS 'Surrogate key for each version of the organisation address record.';
COMMENT ON COLUMN ods.organisation_addresses.valid_from IS 'Timestamp at which this version becomes valid.';
COMMENT ON COLUMN ods.organisation_addresses.valid_to IS 'Timestamp at which this version ceases to be valid.';
COMMENT ON COLUMN ods.organisation_addresses.is_current IS 'TRUE if this row is the current version.';
