-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero OrganisationExternalLinks
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses IDENTITY.
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Composite natural key: organisation_id + link_type (one external link per type).
-- =============================================================

/* -------------------------------------------------------------
   ods.organisation_external_links – social / website links for organisations
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.organisation_external_links (
    /* --- Business / natural key -------------------------------- */
    organisation_id UUID        NOT NULL,
    link_type       VARCHAR(20) NOT NULL,

    /* --- Scalar attributes (ExternalLink schema) ---------------- */
    url         VARCHAR(2048) NOT NULL,
    description VARCHAR(255),

    /* --- SCD‑2 infrastructure ---------------------------------- */
    surrogate_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from    TIMESTAMPTZ NOT NULL,
    valid_to      TIMESTAMPTZ NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current    BOOLEAN     NOT NULL DEFAULT TRUE,

    /* --- Audit & status ---------------------------------------- */
    fetched_at     TIMESTAMPTZ NOT NULL,
    row_created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status  ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking ------------------------------- */
    batch_id                  UUID         NOT NULL,
    landing_table_name        VARCHAR(255) NOT NULL,
    landing_record_identifier VARCHAR(512) NOT NULL,
    raw_table_name            VARCHAR(255),
    api_call_id               UUID,
    source_system_id          VARCHAR(100),
    source_record_modified_at TIMESTAMPTZ,

    /* --- Constraints ------------------------------------------- */
    CONSTRAINT uq_org_external_links_business_key_current
        UNIQUE (organisation_id, link_type, is_current) WHERE is_current,

    CONSTRAINT fk_org_external_links_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES ods.organisations(organisation_id),

    CONSTRAINT ck_org_external_links_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),

    CONSTRAINT ck_org_external_links_valid_dates
        CHECK (valid_from < valid_to),

    CONSTRAINT ck_org_external_links_type
        CHECK (link_type IN ('Facebook','GooglePlus','LinkedIn','Twitter','Website'))
);

/* --- Indexes -------------------------------------------------- */
CREATE INDEX IF NOT EXISTS idx_org_external_links_business_key_current
    ON ods.organisation_external_links(organisation_id, link_type) WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_org_external_links_valid_to
    ON ods.organisation_external_links(valid_to);

CREATE INDEX IF NOT EXISTS idx_org_external_links_is_current
    ON ods.organisation_external_links(is_current);

CREATE INDEX IF NOT EXISTS idx_org_external_links_fetched_at
    ON ods.organisation_external_links(fetched_at);

CREATE INDEX IF NOT EXISTS idx_org_external_links_batch_id
    ON ods.organisation_external_links(batch_id);

/* --- Row‑updated‑at trigger ---------------------------------- */
CREATE TRIGGER trg_update_org_external_links_row_updated_at
BEFORE UPDATE ON ods.organisation_external_links
FOR EACH ROW EXECUTE FUNCTION fn_update_row_updated_at();

/* --- Documentation ------------------------------------------- */
COMMENT ON TABLE ods.organisation_external_links IS 'External links (Facebook, Twitter, Website, etc.) for Xero organisations, stored as a Type‑2 SCD to track history.';
COMMENT ON COLUMN ods.organisation_external_links.organisation_id IS 'Foreign key to ods.organisations (business key).';
COMMENT ON COLUMN ods.organisation_external_links.link_type IS 'External link type: Facebook, GooglePlus, LinkedIn, Twitter or Website.';
COMMENT ON COLUMN ods.organisation_external_links.url IS 'URL for the external link.';
COMMENT ON COLUMN ods.organisation_external_links.surrogate_key IS 'Surrogate key for each version of the organisation external link record.';
COMMENT ON COLUMN ods.organisation_external_links.valid_from IS 'Timestamp at which this version becomes valid.';
COMMENT ON COLUMN ods.organisation_external_links.valid_to IS 'Timestamp at which this version ceases to be valid.';
COMMENT ON COLUMN ods.organisation_external_links.is_current IS 'TRUE if this row is the current version.';
