-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero Organisations
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses IDENTITY (no SERIAL).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Arrays / nested objects (Addresses, Phones, ExternalLinks, PaymentTerms, etc.)
--      are not expanded here – request if separate SCD‑2 tables are required.
-- =============================================================

/* -------------------------------------------------------------
   ods.organisations – master tenant dimension (Type‑2 SCD)
-------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.organisations (
    /* --- Business / natural key -------------------------------- */
    organisation_id UUID NOT NULL,

    /* --- Core scalar attributes from Organisation schema -------- */
    api_key                        VARCHAR(100),
    name                           VARCHAR(255),
    legal_name                     VARCHAR(255),
    pays_tax                       BOOLEAN,
    version                        VARCHAR(20),  -- enum, see constraint ck_org_version
    organisation_type              VARCHAR(40),  -- enum, see ck_org_type
    base_currency                  CHAR(3),
    country_code                   CHAR(2),
    is_demo_company                BOOLEAN,
    organisation_status            VARCHAR(20),
    registration_number            VARCHAR(50),
    employer_identification_number VARCHAR(50),
    tax_number                     VARCHAR(50),
    financial_year_end_day         SMALLINT,   -- 0‑31
    financial_year_end_month       SMALLINT,   -- 1‑12
    sales_tax_basis                VARCHAR(25), -- enum, ck_sales_tax_basis
    sales_tax_period               VARCHAR(25), -- enum, ck_sales_tax_period
    default_sales_tax              VARCHAR(50),
    default_purchases_tax          VARCHAR(50),
    period_lock_date               DATE,
    end_of_year_lock_date          DATE,
    created_date_utc               TIMESTAMPTZ,
    timezone                       VARCHAR(60),
    organisation_entity_type       VARCHAR(40),
    short_code                     VARCHAR(20),
    class                          VARCHAR(20),  -- enum, ck_org_class
    edition                        VARCHAR(10),  -- enum, ck_org_edition
    line_of_business               VARCHAR(255),

    /* --- SCD‑2 infrastructure ---------------------------------- */
    surrogate_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from    TIMESTAMPTZ NOT NULL,
    valid_to      TIMESTAMPTZ NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current    BOOLEAN     NOT NULL DEFAULT TRUE,

    /* --- Audit & status ---------------------------------------- */
    fetched_at     TIMESTAMPTZ NOT NULL,
    row_created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status  ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking ------------------------------- */
    batch_id                  UUID         NOT NULL,
    landing_table_name        VARCHAR(255) NOT NULL,
    landing_record_identifier VARCHAR(512) NOT NULL,
    raw_table_name            VARCHAR(255),
    api_call_id               UUID,
    source_system_id          VARCHAR(100),
    source_record_modified_at TIMESTAMPTZ,

    /* --- Constraints ------------------------------------------- */


    CONSTRAINT ck_org_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),

    CONSTRAINT ck_org_valid_dates
        CHECK (valid_from < valid_to),

    CONSTRAINT ck_org_fye_day
        CHECK (financial_year_end_day BETWEEN 0 AND 31),

    CONSTRAINT ck_org_fye_month
        CHECK (financial_year_end_month BETWEEN 1 AND 12),

    CONSTRAINT ck_org_version
        CHECK (version IN ('AU','NZ','GLOBAL','UK','US','AUONRAMP','NZONRAMP','GLOBALONRAMP','UKONRAMP','USONRAMP')),

    CONSTRAINT ck_org_type
        CHECK (organisation_type IN (
            'ACCOUNTING_PRACTICE','COMPANY','CHARITY','CLUB_OR_SOCIETY','INDIVIDUAL',
            'LOOK_THROUGH_COMPANY','NOT_FOR_PROFIT','PARTNERSHIP','S_CORPORATION',
            'SELF_MANAGED_SUPERANNUATION_FUND','SOLE_TRADER','SUPERANNUATION_FUND','TRUST')),

    CONSTRAINT ck_sales_tax_basis
        CHECK (sales_tax_basis IN ('PAYMENTS','INVOICE','NONE','CASH','ACCRUAL','FLATRATECASH','FLATRATEACCRUAL','ACCRUALS')),

    CONSTRAINT ck_sales_tax_period
        CHECK (sales_tax_period IN (
            'MONTHLY','QUARTERLY1','QUARTERLY2','QUARTERLY3','ANNUALLY','ONEMONTHS','TWOMONTHS','SIXMONTHS',
            '1MONTHLY','2MONTHLY','3MONTHLY','6MONTHLY','QUARTERLY','YEARLY','NONE')),

    CONSTRAINT ck_org_class
        CHECK (class IN ('DEMO','TRIAL','STARTER','STANDARD','PREMIUM','PREMIUM_20','PREMIUM_50','PREMIUM_100',
                          'LEDGER','GST_CASHBOOK','NON_GST_CASHBOOK','ULTIMATE','LITE','ULTIMATE_10','ULTIMATE_20',
                          'ULTIMATE_50','ULTIMATE_100','IGNITE','GROW','COMPREHENSIVE','SIMPLE')),

    CONSTRAINT ck_org_edition
        CHECK (edition IN ('BUSINESS','PARTNER'))
);

/* --- Indexes -------------------------------------------------- */
CREATE INDEX IF NOT EXISTS idx_organisations_business_key_current
    ON ods.organisations(organisation_id) WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_organisations_valid_to
    ON ods.organisations(valid_to);

CREATE INDEX IF NOT EXISTS idx_organisations_is_current
    ON ods.organisations(is_current);

CREATE INDEX IF NOT EXISTS idx_organisations_fetched_at
    ON ods.organisations(fetched_at);

CREATE INDEX IF NOT EXISTS idx_organisations_batch_id
    ON ods.organisations(batch_id);

/* --- Row‑updated‑at trigger ---------------------------------- */
CREATE TRIGGER trg_update_organisations_row_updated_at
BEFORE UPDATE ON ods.organisations
FOR EACH ROW EXECUTE FUNCTION ods.fn_update_row_updated_at();

/* --- Documentation ------------------------------------------- */
COMMENT ON TABLE ods.organisations IS 'Master Xero tenant table. Type‑2 SCD keeps historical snapshots of organisation metadata.';
COMMENT ON COLUMN ods.organisations.organisation_id IS 'Natural business key – Xero OrganisationID.';
COMMENT ON COLUMN ods.organisations.surrogate_key IS 'Surrogate key for each version of the organisation record.';
COMMENT ON COLUMN ods.organisations.valid_from IS 'Timestamp at which this version becomes valid.';
COMMENT ON COLUMN ods.organisations.valid_to IS 'Timestamp at which this version ceases to be valid.';
COMMENT ON COLUMN ods.organisations.is_current IS 'TRUE if this row is the current version.';

