-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero Prepayments
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses BIGINT IDENTITY (PostgreSQL‑preferred).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Business key: prepayment_id (UUID).
--    * Child objects/arrays (LineItems, Allocations, Attachments, Contact) are NOT expanded here – request a table if needed.
-- =============================================================

/* -------------------------------------------------------------
   ods.prepayments – Type‑2 Slowly Changing Dimensions table
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.prepayments (
    /* --- Business / natural key ------------------------------ */
    prepayment_id         UUID            NOT NULL,  -- Xero PrepaymentID

    /* --- Relationship / context keys ------------------------- */
    organisation_id       UUID            NOT NULL,
    contact_id            UUID,
    branding_theme_id     UUID,

    /* --- Core scalar attributes ------------------------------ */
    type                  VARCHAR(20) CHECK (type = 'ACCPREPAYMENT'),
    status                VARCHAR(12) CHECK (status IN ('AUTHORISE','PAID','VOIDED')),
    date                  DATE,
    due_date              DATE,
    line_amount_types     VARCHAR(10) CHECK (line_amount_types IN ('EXCLUSIVE','INCLUSIVE','NOTAX')),
    currency_code         CHAR(3) CHECK (currency_code ~ '^[A-Z]{3}$'),
    currency_rate         NUMERIC(18,6) CHECK (currency_rate >= 0),
    sub_total             NUMERIC(18,2) CHECK (sub_total >= 0),
    total_tax             NUMERIC(18,2) CHECK (total_tax >= 0),
    total                 NUMERIC(18,2) CHECK (total >= 0),
    amount_due            NUMERIC(18,2) CHECK (amount_due >= 0),
    amount_paid           NUMERIC(18,2) CHECK (amount_paid >= 0),
    fully_paid_on_date    DATE,
    reference             VARCHAR(255),
    url                   VARCHAR(1000),
    has_attachments       BOOLEAN,
    updated_date_utc      TIMESTAMPTZ,
    status_attribute_string VARCHAR(50),

    /* --- SCD‑2 infrastructure -------------------------------- */
    surrogate_key         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from            TIMESTAMPTZ NOT NULL,
    valid_to              TIMESTAMPTZ NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current            BOOLEAN     NOT NULL DEFAULT TRUE,

    /* --- Audit & status -------------------------------------- */
    fetched_at            TIMESTAMPTZ NOT NULL,
    row_created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status         ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking ----------------------------- */
    batch_id                     UUID         NOT NULL,
    landing_table_name           VARCHAR(255) NOT NULL,
    landing_record_identifier    VARCHAR(512) NOT NULL,
    raw_table_name               VARCHAR(255),
    api_call_id                  UUID,
    source_system_id             VARCHAR(100),
    source_record_modified_at    TIMESTAMPTZ,

    /* --- Constraints ----------------------------------------- */
    CONSTRAINT uq_prepayments_business_key_current
        UNIQUE (prepayment_id, is_current)
        WHERE is_current,

    CONSTRAINT ck_prepayments_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),

    CONSTRAINT ck_prepayments_valid_dates
        CHECK (valid_from < valid_to),

    /* --- Foreign Keys ---------------------------------------- */
    CONSTRAINT fk_prepayments_contact
        FOREIGN KEY (contact_id)
        REFERENCES ods.contacts(contact_id),

    CONSTRAINT fk_prepayments_branding_theme
        FOREIGN KEY (branding_theme_id)
        REFERENCES ods.branding_themes(branding_theme_id),

    CONSTRAINT fk_prepayments_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES ods.organisations(organisation_id)
);

/* --- Indexes -------------------------------------------------- */
CREATE INDEX IF NOT EXISTS idx_prepayments_business_key_current
    ON ods.prepayments(prepayment_id) WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_prepayments_contact_id
    ON ods.prepayments(contact_id);

CREATE INDEX IF NOT EXISTS idx_prepayments_valid_to
    ON ods.prepayments(valid_to);

CREATE INDEX IF NOT EXISTS idx_prepayments_is_current
    ON ods.prepayments(is_current);

CREATE INDEX IF NOT EXISTS idx_prepayments_fetched_at
    ON ods.prepayments(fetched_at);

CREATE INDEX IF NOT EXISTS idx_prepayments_batch_id
    ON ods.prepayments(batch_id);

CREATE INDEX IF NOT EXISTS idx_prepayments_organisation_id
    ON ods.prepayments(organisation_id);

/* --- Trigger to maintain row_updated_at ----------------------- */
CREATE TRIGGER trg_update_prepayments_row_updated_at
BEFORE UPDATE ON ods.prepayments
FOR EACH ROW EXECUTE FUNCTION ods.fn_update_row_updated_at();

/* --- Documentation ------------------------------------------- */
COMMENT ON TABLE ods.prepayments IS 'Prepayment records from Xero, stored as Type‑2 slowly changing dimension rows.';
COMMENT ON COLUMN ods.prepayments.prepayment_id IS 'Natural identifier for a prepayment.';
COMMENT ON COLUMN ods.prepayments.contact_id IS 'Optional link to the contact this prepayment relates to.';
COMMENT ON COLUMN ods.prepayments.total IS 'Total amount of the prepayment in the transaction currency.';
COMMENT ON COLUMN ods.prepayments.is_current IS 'TRUE if this row represents the current version of the prepayment record.';
