-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero RepeatingInvoices
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses BIGINT IDENTITY (PostgreSQL‑preferred).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Business key: repeating_invoice_id (UUID).
--    * Child arrays/objects (LineItems, Attachments, Contact) are NOT expanded here – ask if
--      you need separate SCD‑2 tables for them.
-- =============================================================

/* -------------------------------------------------------------
   ods.repeating_invoices – Type‑2 Slowly Changing Dimensions
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.repeating_invoices (
    /* --- Business / natural key -------------------------------- */
    repeating_invoice_id       UUID            NOT NULL,   -- Xero RepeatingInvoiceID

    /* --- Tenant / optional parent links ------------------------ */
    organisation_id            UUID            NOT NULL,
    contact_id                 UUID,
    branding_theme_id          UUID,

    /* --- Core scalar attributes -------------------------------- */
    type                       VARCHAR(6)  NOT NULL CHECK (type IN ('ACCREC','ACCPAY')),
    status                     VARCHAR(10) NOT NULL CHECK (status IN ('DRAFT','AUTHORISED','PAUSED','DELETED')),
    line_amount_types          VARCHAR(9)  CHECK (line_amount_types IN ('EXCLUSIVE','INCLUSIVE','NOTAX')),

    reference                  VARCHAR(255),
    repeating_invoice_number   VARCHAR(50),

    /* --- Schedule details -------------------------------------- */
    schedule_period            VARCHAR(7)   NOT NULL CHECK (schedule_period IN ('WEEKLY','MONTHLY','YEARLY')),
    schedule_frequency         INTEGER      NOT NULL CHECK (schedule_frequency > 0),
    schedule_due_days          INTEGER      CHECK (schedule_due_days >= 0),
    start_date                 DATE         NOT NULL,
    next_scheduled_date        DATE,
    end_date                   DATE,

    /* --- Monetary & currency ----------------------------------- */
    currency_code              VARCHAR(3)   CHECK (currency_code ~ '^[A-Z]{3}$'),
    currency_rate              NUMERIC(18,6) CHECK (currency_rate >= 0),
    sub_total                  NUMERIC(18,2) CHECK (sub_total >= 0),
    total_tax                  NUMERIC(18,2) CHECK (total_tax >= 0),
    total                      NUMERIC(18,2) CHECK (total >= 0),
    has_attachments            BOOLEAN,

    updated_date_utc           TIMESTAMPTZ,

    /* --- SCD‑2 infrastructure ---------------------------------- */
    surrogate_key              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from                 TIMESTAMPTZ NOT NULL,
    valid_to                   TIMESTAMPTZ NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current                 BOOLEAN NOT NULL DEFAULT TRUE,

    /* --- Audit & status ---------------------------------------- */
    fetched_at                 TIMESTAMPTZ NOT NULL,
    row_created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status              ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking ------------------------------- */
    batch_id                   UUID         NOT NULL,
    landing_table_name         VARCHAR(255) NOT NULL,
    landing_record_identifier  VARCHAR(512) NOT NULL,
    raw_table_name             VARCHAR(255),
    api_call_id                UUID,
    source_system_id           VARCHAR(100),
    source_record_modified_at  TIMESTAMPTZ,

    /* --- Constraints ------------------------------------------- */
    CONSTRAINT uq_repeating_invoices_business_key_current UNIQUE (repeating_invoice_id, is_current) WHERE is_current,

    CONSTRAINT ck_repeating_invoices_record_status CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),
    CONSTRAINT ck_repeating_invoices_valid_dates   CHECK (valid_from < valid_to),

    /* --- Foreign Keys ------------------------------------------ */
    CONSTRAINT fk_repeat_inv_org FOREIGN KEY (organisation_id)
        REFERENCES ods.organisations(organisation_id)
);

/* --- Indexes --------------------------------------------------- */
CREATE INDEX IF NOT EXISTS idx_repeating_invoices_business_key_current ON ods.repeating_invoices(repeating_invoice_id) WHERE is_current;
CREATE INDEX IF NOT EXISTS idx_repeating_invoices_org_id              ON ods.repeating_invoices(organisation_id);
CREATE INDEX IF NOT EXISTS idx_repeating_invoices_valid_to            ON ods.repeating_invoices(valid_to);
CREATE INDEX IF NOT EXISTS idx_repeating_invoices_is_current          ON ods.repeating_invoices(is_current);
CREATE INDEX IF NOT EXISTS idx_repeating_invoices_fetched_at          ON ods.repeating_invoices(fetched_at);
CREATE INDEX IF NOT EXISTS idx_repeating_invoices_batch_id            ON ods.repeating_invoices(batch_id);

/* --- Trigger to maintain row_updated_at ------------------------ */
CREATE TRIGGER trg_update_repeating_invoices_row_updated_at
BEFORE UPDATE ON ods.repeating_invoices
FOR EACH ROW EXECUTE FUNCTION fn_update_row_updated_at();

/* --- Documentation -------------------------------------------- */
COMMENT ON TABLE ods.repeating_invoices IS 'Stores Xero Repeating Invoices as Type‑2 slowly changing dimensions (one row per repeating‑invoice template version).';
COMMENT ON COLUMN ods.repeating_invoices.repeating_invoice_id IS 'Natural business key (Xero RepeatingInvoiceID) for a repeating invoice template.';
COMMENT ON COLUMN ods.repeating_invoices.schedule_frequency IS 'Frequency multiplier – e.g. every 2 weeks, every 3 months, etc.';
