-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero TaxRateComponents
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses IDENTITY (PostgreSQL‑preferred).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Composite business key: organisation_id + tax_type + name (component name).
--    * Parent‑level arrays (none) – all fields are scalar here.
-- =============================================================

/* -------------------------------------------------------------
   ods.tax_rate_components – individual components of each TaxRate
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.tax_rate_components (
    /* --- Business / natural keys ----------------------------- */
    organisation_id UUID         NOT NULL,           -- Tenant / organisation
    tax_type        VARCHAR(50)  NOT NULL,           -- Parent TaxRate business key
    name            VARCHAR(255) NOT NULL,           -- Component name (e.g. GST, PST)

    /* --- Core attributes from TaxComponent schema ------------ */
    rate               NUMERIC(10,4) NOT NULL,       -- Component rate (up to 4dp) fileciteturn25file3
    is_compound        BOOLEAN NOT NULL DEFAULT FALSE,
    is_non_recoverable BOOLEAN NOT NULL DEFAULT FALSE,

    /* --- SCD‑2 infrastructure -------------------------------- */
    surrogate_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from    TIMESTAMPTZ NOT NULL,
    valid_to      TIMESTAMPTZ NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current    BOOLEAN     NOT NULL DEFAULT TRUE,

    /* --- Audit & status -------------------------------------- */
    fetched_at     TIMESTAMPTZ NOT NULL,
    row_created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status  ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking ----------------------------- */
    batch_id                  UUID         NOT NULL,
    landing_table_name        VARCHAR(255) NOT NULL,
    landing_record_identifier VARCHAR(512) NOT NULL,
    raw_table_name            VARCHAR(255),
    api_call_id               UUID,
    source_system_id          VARCHAR(100),
    source_record_modified_at TIMESTAMPTZ,

    /* --- Constraints ----------------------------------------- */
    CONSTRAINT uq_tax_rate_components_business_key_current
        UNIQUE (organisation_id, tax_type, name, is_current)
        WHERE is_current,

    -- Optional: validate numeric bounds
    CONSTRAINT ck_tax_rate_components_rate_non_negative
        CHECK (rate >= 0),

    -- Generic SCD & status checks
    CONSTRAINT ck_tax_rate_components_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),

    CONSTRAINT ck_tax_rate_components_valid_dates
        CHECK (valid_from < valid_to)
);

/* --- Indexes -------------------------------------------------- */
CREATE INDEX IF NOT EXISTS idx_tax_rate_components_business_key_current
    ON ods.tax_rate_components(organisation_id, tax_type, name)
    WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_tax_rate_components_valid_to
    ON ods.tax_rate_components(valid_to);

CREATE INDEX IF NOT EXISTS idx_tax_rate_components_is_current
    ON ods.tax_rate_components(is_current);

CREATE INDEX IF NOT EXISTS idx_tax_rate_components_fetched_at
    ON ods.tax_rate_components(fetched_at);

CREATE INDEX IF NOT EXISTS idx_tax_rate_components_batch_id
    ON ods.tax_rate_components(batch_id);

/* --- Trigger to maintain row_updated_at ----------------------- */
CREATE TRIGGER trg_update_tax_rate_components_row_updated_at
BEFORE UPDATE ON ods.tax_rate_components
FOR EACH ROW EXECUTE FUNCTION fn_update_row_updated_at();

/* --- Documentation ------------------------------------------- */
COMMENT ON TABLE ods.tax_rate_components IS 'Tax‑rate component breakdowns (e.g. GST, PST) stored as a Type‑2 SCD.';
COMMENT ON COLUMN ods.tax_rate_components.organisation_id IS 'Tenant foreign‑key – identifies the organisation.';
COMMENT ON COLUMN ods.tax_rate_components.tax_type IS 'TaxRate business key to which this component belongs.';
COMMENT ON COLUMN ods.tax_rate_components.name IS 'Component name (business key within a tax rate).';
COMMENT ON COLUMN ods.tax_rate_components.rate IS 'Component rate expressed to four decimal places.';
COMMENT ON COLUMN ods.tax_rate_components.surrogate_key IS 'Surrogate key for each version of the component record.';
COMMENT ON COLUMN ods.tax_rate_components.valid_from IS 'Timestamp at which this version becomes valid.';
COMMENT ON COLUMN ods.tax_rate_components.valid_to IS 'Timestamp at which this version ceases to be valid.';
COMMENT ON COLUMN ods.tax_rate_components.is_current IS 'TRUE if this row represents the current version.';
