-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero TrackingOptions
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses IDENTITY (PostgreSQL‑preferred).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Business key: tracking_option_id (UUID).
--    * Parent linkage via tracking_category_id + organisation_id (no FK to type‑2 table).
--    * All CHECK constraints added; trailing whitespace removed.
-- =============================================================

/* -------------------------------------------------------------
   ods.tracking_options – individual options within a category
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.tracking_options (
    /* --- Business / natural key ----------------------------- */
    tracking_option_id  UUID         NOT NULL,  -- Xero TrackingOptionID

    /* --- Core attributes from TrackingOption schema --------- */
    tracking_category_id UUID        NOT NULL,
    organisation_id      UUID        NOT NULL,  -- Tenant / organisation FK
    name                 VARCHAR(100) NOT NULL,  -- Option name (≤100 chars)
    status               VARCHAR(20)  NOT NULL,  -- ACTIVE | ARCHIVED | DELETED
    has_validation_errors BOOLEAN     NOT NULL DEFAULT FALSE,

    /* --- SCD‑2 infrastructure ------------------------------ */
    surrogate_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from    TIMESTAMPTZ NOT NULL,
    valid_to      TIMESTAMPTZ NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current    BOOLEAN     NOT NULL DEFAULT TRUE,

    /* --- Audit & status ------------------------------------ */
    fetched_at     TIMESTAMPTZ NOT NULL,
    row_created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status  ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking --------------------------- */
    batch_id                  UUID         NOT NULL,
    landing_table_name        VARCHAR(255) NOT NULL,
    landing_record_identifier VARCHAR(512) NOT NULL,
    raw_table_name            VARCHAR(255),
    api_call_id               UUID,
    source_system_id          VARCHAR(100),
    source_record_modified_at TIMESTAMPTZ,

    /* --- Constraints --------------------------------------- */
    CONSTRAINT uq_tracking_options_business_key_current
        UNIQUE (tracking_option_id, is_current)
        WHERE is_current,

    CONSTRAINT fk_tracking_options_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES ods.organisations(organisation_id),

    CONSTRAINT ck_tracking_options_status_allowed
        CHECK (status IN ('ACTIVE','ARCHIVED','DELETED')),

    CONSTRAINT ck_tracking_options_name_not_blank
        CHECK (char_length(trim(name)) > 0),

    -- Generic SCD & status checks
    CONSTRAINT ck_tracking_options_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),

    CONSTRAINT ck_tracking_options_valid_dates
        CHECK (valid_from < valid_to)
);

/* --- Indexes ------------------------------------------------ */
CREATE INDEX IF NOT EXISTS idx_tracking_options_business_key_current
    ON ods.tracking_options(tracking_option_id)
    WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_tracking_options_valid_to
    ON ods.tracking_options(valid_to);

CREATE INDEX IF NOT EXISTS idx_tracking_options_is_current
    ON ods.tracking_options(is_current);

CREATE INDEX IF NOT EXISTS idx_tracking_options_fetched_at
    ON ods.tracking_options(fetched_at);

CREATE INDEX IF NOT EXISTS idx_tracking_options_batch_id
    ON ods.tracking_options(batch_id);

/* --- Trigger to maintain row_updated_at -------------------- */
CREATE TRIGGER trg_update_tracking_options_row_updated_at
BEFORE UPDATE ON ods.tracking_options
FOR EACH ROW EXECUTE FUNCTION ods.fn_update_row_updated_at();

/* --- Documentation ---------------------------------------- */
COMMENT ON TABLE ods.tracking_options IS 'Tracking category options (child of tracking_categories); stored as Type‑2 SCD.';
COMMENT ON COLUMN ods.tracking_options.tracking_option_id IS 'Natural business key (Xero TrackingOptionID).';
COMMENT ON COLUMN ods.tracking_options.tracking_category_id IS 'Parent tracking category (Xero TrackingCategoryID).';
COMMENT ON COLUMN ods.tracking_options.name IS 'Name of the tracking option (≤100 characters).';
COMMENT ON COLUMN ods.tracking_options.status IS 'Status of the option – ACTIVE, ARCHIVED, or DELETED.';
COMMENT ON COLUMN ods.tracking_options.surrogate_key IS 'Surrogate key for each version of the tracking option.';
COMMENT ON COLUMN ods.tracking_options.valid_from IS 'Timestamp when this version becomes valid.';
COMMENT ON COLUMN ods.tracking_options.valid_to IS 'Timestamp when this version ceases to be valid.';
COMMENT ON COLUMN ods.tracking_options.is_current IS 'TRUE if this row represents the current version.';
