-- =============================================================
--  ODS SCD‑2 DDL SCRIPT – Xero Users
--  Generated: 28‑May‑2025
--  Notes:
--    * Surrogate key uses BIGINT IDENTITY (PostgreSQL‑preferred).
--    * Assumes ods.record_status_enum and fn_update_row_updated_at() already exist.
--    * Business key: user_id (UUID).
-- =============================================================

/* -------------------------------------------------------------
   ods.users – Xero organisation users as Type‑2 SCD records
   ------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS ods.users (
    /* --- Business / natural key ----------------------------- */
    user_id            UUID            NOT NULL, -- Xero UserID

    /* --- Relationship keys ---------------------------------- */
    organisation_id    UUID            NOT NULL,

    /* --- Core scalar attributes ----------------------------- */
    email_address      VARCHAR(255),
    first_name         VARCHAR(255),
    last_name          VARCHAR(255),
    updated_date_utc   TIMESTAMPTZ,
    is_subscriber      BOOLEAN,
    organisation_role  VARCHAR(20),

    /* --- SCD‑2 infrastructure ------------------------------- */
    surrogate_key      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valid_from         TIMESTAMPTZ     NOT NULL,
    valid_to           TIMESTAMPTZ     NOT NULL DEFAULT '9999-12-31 23:59:59.999999+00',
    is_current         BOOLEAN         NOT NULL DEFAULT TRUE,

    /* --- Audit & status ------------------------------------- */
    fetched_at         TIMESTAMPTZ     NOT NULL,
    row_created_at     TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_updated_at     TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    record_status      ods.record_status_enum NOT NULL DEFAULT 'ACTIVE',

    /* --- Batch / source tracking ---------------------------- */
    batch_id                  UUID         NOT NULL,
    landing_table_name        VARCHAR(255) NOT NULL,
    landing_record_identifier VARCHAR(512) NOT NULL,
    raw_table_name            VARCHAR(255),
    api_call_id               UUID,
    source_system_id          VARCHAR(100),
    source_record_modified_at TIMESTAMPTZ,

    /* --- Constraints ---------------------------------------- */
    CONSTRAINT uq_users_business_key_current
        UNIQUE (user_id, is_current) WHERE is_current,

    CONSTRAINT fk_users_organisation
        FOREIGN KEY (organisation_id)
        REFERENCES ods.organisations(organisation_id),

    CONSTRAINT ck_users_org_role
        CHECK (organisation_role IS NULL OR organisation_role IN (
            'READONLY','INVOICEONLY','STANDARD','FINANCIALADVISER',
            'MANAGEDCLIENT','CASHBOOKCLIENT','UNKNOWN'
        )),

    CONSTRAINT ck_users_record_status
        CHECK (record_status IN ('ACTIVE','SUPERSEDED','ARCHIVED','REMOVED')),

    CONSTRAINT ck_users_valid_dates
        CHECK (valid_from < valid_to)
);

/* --- Indexes ------------------------------------------------ */
CREATE INDEX IF NOT EXISTS idx_users_business_key_current
    ON ods.users(user_id) WHERE is_current;

CREATE INDEX IF NOT EXISTS idx_users_valid_to
    ON ods.users(valid_to);

CREATE INDEX IF NOT EXISTS idx_users_is_current
    ON ods.users(is_current);

CREATE INDEX IF NOT EXISTS idx_users_fetched_at
    ON ods.users(fetched_at);

CREATE INDEX IF NOT EXISTS idx_users_batch_id
    ON ods.users(batch_id);

CREATE INDEX IF NOT EXISTS idx_users_organisation_id
    ON ods.users(organisation_id);

/* --- Trigger to maintain row_updated_at -------------------- */
CREATE TRIGGER trg_update_users_row_updated_at
BEFORE UPDATE ON ods.users
FOR EACH ROW EXECUTE FUNCTION ods.fn_update_row_updated_at();

/* --- Documentation ----------------------------------------- */
COMMENT ON TABLE ods.users IS 'Users of the Xero organisation captured as Type‑2 slowly‑changing dimensions.';
COMMENT ON COLUMN ods.users.user_id IS 'Xero UserID (business key).';
COMMENT ON COLUMN ods.users.organisation_id IS 'Tenant organisation that the user belongs to.';
COMMENT ON COLUMN ods.users.organisation_role IS 'Role of the user within Xero (READONLY, INVOICEONLY, etc.).';
COMMENT ON COLUMN ods.users.is_current IS 'TRUE if this row represents the current version of the user record.';
