name: CI

on:
  push:
    branches: [ "**" ]          # every branch push
  pull_request:
    branches: [ "**" ]          # every PR

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # -----------------------------------------------------------------------
      # 1.  Check out the code
      # -----------------------------------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3

      # -----------------------------------------------------------------------
      # 2.  .NET build & tests
      # -----------------------------------------------------------------------
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Build .NET solution
        run: dotnet build --no-restore --configuration Release

      - name: Run .NET tests
        run: dotnet test --no-build --configuration Release
